# Generated by Django 4.0.7 on 2022-10-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='lon',
            field=models.FloatField(blank=True),
        ),
    ]
